
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { 
  Download, 
  FileText, 
  FileImage, 
  File
} from "lucide-react";
import { toast } from "sonner";

interface ExportOptionsProps {
  prompt: string;
  metadata?: {
    platform?: string;
    score?: number;
    timestamp?: Date;
  };
}

export const ExportOptions = ({ prompt, metadata }: ExportOptionsProps) => {
  const [exportFormat, setExportFormat] = useState<string>('');
  const [isExporting, setIsExporting] = useState(false);

  const exportAsTXT = () => {
    const content = `
Generated Prompt
================

Platform: ${metadata?.platform || 'Unknown'}
Score: ${metadata?.score || 'N/A'}/100
Generated: ${metadata?.timestamp?.toLocaleString() || new Date().toLocaleString()}

Prompt:
${prompt}

---
Generated by PromptNovaX
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prompt-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportAsPDF = async () => {
    try {
      setIsExporting(true);
      
      // Simple PDF generation using a canvas approach
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      canvas.width = 800;
      canvas.height = 600;
      
      // White background
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      
      // Title
      ctx.fillStyle = '#000000';
      ctx.font = '24px Arial';
      ctx.fillText('Generated Prompt', 50, 50);
      
      // Metadata
      ctx.font = '14px Arial';
      ctx.fillText(`Platform: ${metadata?.platform || 'Unknown'}`, 50, 90);
      ctx.fillText(`Score: ${metadata?.score || 'N/A'}/100`, 50, 110);
      ctx.fillText(`Generated: ${metadata?.timestamp?.toLocaleString() || new Date().toLocaleString()}`, 50, 130);
      
      // Prompt (word wrap)
      const words = prompt.split(' ');
      let line = '';
      let y = 170;
      const maxWidth = 700;
      
      for (let i = 0; i < words.length; i++) {
        const testLine = line + words[i] + ' ';
        const metrics = ctx.measureText(testLine);
        
        if (metrics.width > maxWidth && i > 0) {
          ctx.fillText(line, 50, y);
          line = words[i] + ' ';
          y += 20;
        } else {
          line = testLine;
        }
      }
      ctx.fillText(line, 50, y);
      
      // Convert to blob and download
      canvas.toBlob((blob) => {
        if (blob) {
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `prompt-${Date.now()}.png`; // Using PNG as simple PDF alternative
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
        }
      });
      
      toast.success("Prompt exported as image!");
    } catch (error) {
      toast.error("Export failed");
    } finally {
      setIsExporting(false);
    }
  };

  const exportAsJSON = () => {
    const data = {
      prompt,
      metadata: {
        platform: metadata?.platform,
        score: metadata?.score,
        timestamp: metadata?.timestamp?.toISOString(),
        exportedAt: new Date().toISOString()
      }
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prompt-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExport = async () => {
    if (!exportFormat) {
      toast.error("Please select an export format");
      return;
    }

    setIsExporting(true);
    
    try {
      switch (exportFormat) {
        case 'txt':
          exportAsTXT();
          toast.success("Prompt exported as TXT!");
          break;
        case 'pdf':
          await exportAsPDF();
          break;
        case 'json':
          exportAsJSON();
          toast.success("Prompt exported as JSON!");
          break;
        default:
          toast.error("Unsupported format");
      }
    } catch (error) {
      toast.error("Export failed");
    } finally {
      setIsExporting(false);
    }
  };

  const getFormatIcon = (format: string) => {
    switch (format) {
      case 'txt': return <FileText className="h-4 w-4" />;
      case 'pdf': return <FileImage className="h-4 w-4" />;
      case 'json': return <File className="h-4 w-4" />;
      default: return <Download className="h-4 w-4" />;
    }
  };

  if (!prompt) {
    return (
      <Card>
        <CardContent className="pt-6">
          <div className="text-center py-8 text-gray-500">
            <Download className="h-12 w-12 mx-auto mb-4 opacity-20" />
            <p>No prompt to export</p>
            <p className="text-sm">Generate a prompt first</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center space-x-2">
          <Download className="h-5 w-5" />
          <span>Export Options</span>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <label className="text-sm font-medium mb-2 block">Export Format</label>
          <Select value={exportFormat} onValueChange={setExportFormat}>
            <SelectTrigger>
              <SelectValue placeholder="Choose format" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="txt">
                <div className="flex items-center space-x-2">
                  <FileText className="h-4 w-4" />
                  <span>Text File (.txt)</span>
                </div>
              </SelectItem>
              <SelectItem value="pdf">
                <div className="flex items-center space-x-2">
                  <FileImage className="h-4 w-4" />
                  <span>Image (.png)</span>
                </div>
              </SelectItem>
              <SelectItem value="json">
                <div className="flex items-center space-x-2">
                  <File className="h-4 w-4" />
                  <span>JSON (.json)</span>
                </div>
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        {exportFormat && (
          <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
            <div className="flex items-center space-x-2 mb-2">
              {getFormatIcon(exportFormat)}
              <span className="text-sm font-medium">
                {exportFormat.toUpperCase()} Export
              </span>
            </div>
            <p className="text-xs text-gray-600 dark:text-gray-400">
              {exportFormat === 'txt' && "Plain text file with prompt and metadata"}
              {exportFormat === 'pdf' && "Visual representation as image file"}
              {exportFormat === 'json' && "Structured data format with metadata"}
            </p>
          </div>
        )}

        <div className="flex space-x-2">
          <Button 
            onClick={handleExport}
            disabled={!exportFormat || isExporting}
            className="flex-1"
          >
            {isExporting ? (
              <>Loading...</>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                Export Prompt
              </>
            )}
          </Button>
        </div>

        {metadata && (
          <div className="pt-4 border-t">
            <h4 className="text-sm font-medium mb-2">Export Details</h4>
            <div className="space-y-1 text-xs text-gray-600 dark:text-gray-400">
              {metadata.platform && (
                <div className="flex items-center space-x-2">
                  <span>Platform:</span>
                  <Badge variant="outline" className="text-xs">{metadata.platform}</Badge>
                </div>
              )}
              {metadata.score && (
                <div className="flex items-center space-x-2">
                  <span>Quality Score:</span>
                  <Badge variant="secondary" className="text-xs">{metadata.score}/100</Badge>
                </div>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
};


